### ISSUE TITLE
examples can't work

### ISSUE THREAD

**Issue by longredzhong** [BenWhetton/keras-surgeon#9] opened 2018-07-19 12:40 UTC
Traceback (most recent call last):
  File "lenet_mnist.py", line 107, in <module>
    main()
  File "lenet_mnist.py", line 82, in main
    model = delete_channels(model, layer, high_apoz_channels)
  File "/home/longred/miniconda3/lib/python3.6/site-packages/kerassurgeon/operations.py", line 105, in delete_channels
    return surgeon.operate()
  File "/home/longred/miniconda3/lib/python3.6/site-packages/kerassurgeon/surgeon.py", line 163, in operate
    enumerate(self.model.output_layers_node_indices)]
AttributeError: 'Sequential' object has no attribute 'output_layers_node_indices'

it don't work ,I don't komw how to fix

**Comment by BenWhetton** [comment] 2018-08-07 20:03
Duplicate of #8.
Fixed in [0.1.1](https://github.com/BenWhetton/keras-surgeon/releases/tag/0.1.1)

**Closed by BenWhetton** 2018-08-07 20:03 UTC
